/**
 * File Name: Main
 * Programmer: Inaam Azeezur-Rahman, Edlyn Li, Nevin D'Souza, Noam McCready
 * Date: August 25, 2020
 * Description: This program runs the Main Menu/pre-game screen of our snake program.
 */

import java.awt.*;
import javax.swing.*;

public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        instruct = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        btnInstructions = new javax.swing.JButton();
        btnPlay = new javax.swing.JButton();

        this.setResizable(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        jPanel1.setBackground(new java.awt.Color(51, 153, 0));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Snake");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(190, 30, 110, 43);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(51, 102, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setFocusable(false);
        jTextArea1.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        jScrollPane1.setViewportView(jTextArea1);
        
        instruct.setEditable(false);
        instruct.setFont(new java.awt.Font("Lucida Grade", 1, 25));
        instruct.setForeground(Color.BLACK);
        instruct.setBackground(new java.awt.Color(51, 153, 0));
        instruct.setBounds(28, 100, 450, 200);
        instruct.setFocusable(false);
        instruct.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        jPanel1.add(instruct);
        instruct.setVisible(false);
        
        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(-10, 20, 510, 60);

        jButton1.setBackground(new java.awt.Color(51, 102, 0));
        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 10)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Exit");
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(400, 310, 80, 30);

        btnInstructions.setBackground(new java.awt.Color(51, 102, 0));
        btnInstructions.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        btnInstructions.setForeground(new java.awt.Color(255, 255, 255));
        btnInstructions.setText("Instructions");
        btnInstructions.setFocusable(false);
        btnInstructions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstructionsActionPerformed(evt);
            }
        }); 
        jPanel1.add(btnInstructions);
        btnInstructions.setBounds(60, 170, 190, 70);

        btnPlay.setBackground(new java.awt.Color(51, 102, 0));
        btnPlay.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        btnPlay.setForeground(new java.awt.Color(255, 255, 255));
        btnPlay.setText("Start");
        btnPlay.setFocusable(false);
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });
        jPanel1.add(btnPlay);
        btnPlay.setBounds(290, 170, 150, 70);
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        if (jButton1.getText().equals("Exit")) {
            dispose();
        } else {
            btnInstructions.setVisible(true);
            btnPlay.setVisible(true);
            instruct.setVisible(false);
            jButton1.setText("Exit");
        }
    }

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
        
        // game area
        JFrame frame = new JFrame();
        Game game = new Game();

        frame.setBounds(10, 10, 910, 655);
        frame.setBackground(Color.DARK_GRAY);
        frame.setResizable(false);
        frame.setVisible(true);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.add(game);
    }
    
    private void btnInstructionsActionPerformed(java.awt.event.ActionEvent evt) {
        btnInstructions.setVisible(false);
        instruct.setVisible(true);
        instruct.setText("Use keyboard arrow keys to move\nUP       DOWN       LEFT       RIGHT" + 
                "\n\nRun into apples to gain points\nDon't let your snake run into itself or it's" +
                "\nGAME OVER!");
        btnPlay.setVisible(false);
        jButton1.setText("Back");
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify  
    private javax.swing.JButton btnInstructions;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea instruct;
    // End of variables declaration                   
}
